database:
  host: localhost
  port: 3306
  username: root
  password: password
  timeout: 30

backup:
  directory: "backups"
  databases:
    - testdb1
    - testdb2
  batch_size: 5
  concurrency: 3
  timeout: 30m
  retry_count: 3
  retry_delay: 10s
  
  # Backup frequency check configuration
  check_last_backup_time: true      # Enable backup frequency checking
  min_backup_interval: 1h           # Minimum interval between backups (1 hour)
  skip_confirmation: false          # Set to true to skip confirmation prompts

upload:
  enabled: false

logging:
  level: info
  format: clean
  file_format: text
  file_path: log/tenangdb.log

cleanup:
  enabled: false

metrics:
  enabled: false
  port: "8080"