global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # TenangDB metrics exporter
  - job_name: 'tenangdb'
    static_configs:
      - targets: ['tenangdb-exporter:9090']
    scrape_interval: 30s
    metrics_path: '/metrics'
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']