apiVersion: v1
kind: ConfigMap
metadata:
  name: tenangdb-config
  namespace: tenangdb
  labels:
    app: tenangdb
data:
  config.yaml: |
    # TenangDB Configuration File
    # Kubernetes deployment configuration
    
    # Database connection settings
    database:
      host: mysql-service.default.svc.cluster.local  # Replace with your MySQL service
      port: 3306
      username: backup-user  # Will be overridden by secret
      password: ""           # Will be overridden by secret
      timeout: 30
    
      # mydumper provides fast, parallel backups
      mydumper:
        enabled: true
        threads: 4
        chunk_filesize: 100
    
        myloader:
          enabled: true
          threads: 4
    
    # Backup storage and database selection
    backup:
      output_dir: /backups
      databases:
        - production_db
        - analytics_db
        - user_data
      batch_size: 5
      concurrency: 3
    
    # Cloud upload configuration
    upload:
      enabled: true
      destination: "s3:your-backup-bucket/tenangdb"  # Configure your cloud storage
      rclone_path: /usr/local/bin/rclone
      timeout: 300
      retry_count: 3
    
    # Frequency checking (requires persistent volume)
    frequency:
      enabled: true
      interval: 24h
      tracking_file: /tmp/tenangdb/backup_tracking.json
    
    # Logging settings
    logging:
      level: info
      format: json  # JSON format for better Kubernetes log integration
      output_file: /var/log/tenangdb/tenangdb.log