apiVersion: v1
kind: ConfigMap
metadata:
  name: tenangdb-config
  namespace: tenangdb
  labels:
    app: tenangdb
data:
  config.yaml: |
    # TenangDB Configuration File
    # Kubernetes deployment configuration
    
    # Database connection settings
    database:
      host: mysql-service.default.svc.cluster.local  # Replace with your MySQL service
      port: 3306
      username: backup-user  # Will be overridden by secret
      password: ""           # Will be overridden by secret
      timeout: 30
    
      # mydumper provides fast, parallel backups
      mydumper:
        enabled: true
        threads: 4
        chunk_filesize: 100
    
        myloader:
          enabled: true
          threads: 4
    
    # Backup storage and database selection
    backup:
      directory: /data/backups
      databases:
        - production_db
        - analytics_db
        - user_data
      batch_size: 5
      concurrency: 3
    
    # Cloud upload configuration
    upload:
      enabled: true
      destination: "gcs:your-tenangdb-backups/backups"
      timeout: 600
      retry_count: 3
      rclone_config_path: "/etc/rclone/rclone.conf"
    
    # Frequency checking (requires persistent volume)
    frequency:
      enabled: true
      interval: 24h
    
    # Metrics configuration
    metrics:
      enabled: true
      storage_path: /data/metrics/metrics.json
      port: "9090"
    
    # Logging settings
    logging:
      level: info
      format: json