apiVersion: batch/v1
kind: CronJob
metadata:
  name: tenangdb-backup
  namespace: tenangdb
  labels:
    app: tenangdb
spec:
  # Schedule: Daily at 2 AM
  schedule: "0 2 * * *"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  # Timezone (optional, requires Kubernetes 1.25+)
  timeZone: "Asia/Jakarta"
  
  # Job configuration
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: tenangdb
            job-type: backup
        spec:
          serviceAccountName: tenangdb
          restartPolicy: OnFailure
          
          # Security context
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            fsGroup: 1001
            fsGroupChangePolicy: "OnRootMismatch"
          
          containers:
          - name: tenangdb
            image: ghcr.io/abdullahainun/tenangdb:latest
            imagePullPolicy: Always
            
            # Command - use the main binary
            command: ["/tenangdb"]
            args: ["backup", "--force", "--config", "/config.yaml"]
            
            
            # Volume mounts
            volumeMounts:
            - name: config
              mountPath: /config.yaml
              subPath: config.yaml
              readOnly: true
            - name: data
              mountPath: /data
            
            # Resource limits
            resources:
              requests:
                memory: "512Mi"
                cpu: "500m"
              limits:
                memory: "2Gi"
                cpu: "2000m"
          
          volumes:
          - name: config
            configMap:
              name: tenangdb-config
          - name: data
            persistentVolumeClaim:
              claimName: pvc-tenangdb-data

---
# Optional: Manual backup job template
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: tenangdb-manual-backup
#   namespace: tenangdb
#   labels:
#     app: tenangdb
#     job-type: manual
# spec:
#   template:
#     metadata:
#       labels:
#         app: tenangdb
#         job-type: manual
#     spec:
#       serviceAccountName: tenangdb
#       restartPolicy: Never
      
#       securityContext:
#         runAsNonRoot: true
#         runAsUser: 1001
#         runAsGroup: 1001
#         fsGroup: 1001
#         fsGroupChangePolicy: "OnRootMismatch"
      
#       containers:
#       - name: tenangdb
#         image: ghcr.io/abdullahainun/tenangdb:latest
#         imagePullPolicy: Always
        
#         command: ["/tenangdb"]
#         args: ["backup", "--force", "--config", "/config.yaml"]  # Force backup even if frequency check fails    
        
#         volumeMounts:
#         - name: config
#           mountPath: /config.yaml`
#           subPath: config.yaml
#           readOnly: true
#         - name: backups
#           mountPath: /backups
        
#         resources:
#           requests:
#             memory: "512Mi"
#             cpu: "500m"
#           limits:
#             memory: "2Gi"
#             cpu: "2000m"
      
#       volumes:
#       - name: config
#         configMap:
#           name: tenangdb-config
#       - name: backups
#         persistentVolumeClaim:
#           claimName: pvc-tenangdb-backups