apiVersion: v1
kind: Secret
metadata:
  name: tenangdb-gcs-config
  namespace: tenangdb
type: Opaque
stringData:
  rclone.conf: |
    [gcs]
    type = google cloud storage
    project_number = YOUR_PROJECT_NUMBER
    service_account_file = /etc/gcs-key/service-account.json
    location = us-central1
    storage_class = STANDARD
    
  service-account.json: |
    {
      "type": "service_account",
      "project_id": "your-project-id",
      "private_key_id": "your-private-key-id",
      "private_key": "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY\n-----END PRIVATE KEY-----\n",
      "client_email": "tenangdb-backup@your-project.iam.gserviceaccount.com",
      "client_id": "your-client-id",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/tenangdb-backup%40your-project.iam.gserviceaccount.com"
    }