apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tenangdb-data
  namespace: tenangdb
  labels:
    app: tenangdb
    component: storage
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi