apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tenangdb-backups
  namespace: tenangdb
  labels:
    app: tenangdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi  # Adjust based on your backup size requirements
  # Optional: specify storage class
  # storageClassName: standard

---
# PVC for tracking files (frequency checking)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tenangdb-tracking
  namespace: tenangdb
  labels:
    app: tenangdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Small volume for tracking files
  # Optional: specify storage class
  # storageClassName: standard

---
# PVC for logs (optional)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tenangdb-logs
  namespace: tenangdb
  labels:
    app: tenangdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Adjust based on log retention needs
  # Optional: specify storage class
  # storageClassName: standard