apiVersion: v1
kind: Secret
metadata:
  name: tenangdb-secrets
  namespace: tenangdb
  labels:
    app: tenangdb
type: Opaque
data:
  # Base64 encoded values - replace with your actual credentials
  # To encode: echo -n "your-value" | base64
  
  # Database credentials
  MYSQL_USER: YmFja3VwLXVzZXI=           # backup-user
  MYSQL_PASSWORD: eW91ci1zZWN1cmUtcGFzc3dvcmQ=  # your-secure-password
  
  # Optional: Cloud storage credentials (if using S3/GCS)
  # AWS_ACCESS_KEY_ID: ""
  # AWS_SECRET_ACCESS_KEY: ""
  # GOOGLE_APPLICATION_CREDENTIALS: ""
  
  # Optional: Rclone config for cloud upload
  # RCLONE_CONFIG: ""

---
# Example Secret with actual encoded values
# You should create this separately with your real credentials
apiVersion: v1
kind: Secret
metadata:
  name: tenangdb-secrets-example
  namespace: tenangdb
  labels:
    app: tenangdb
    example: "true"
type: Opaque
stringData:
  # Use stringData for easier editing (Kubernetes will encode automatically)
  MYSQL_USER: "backup-user"
  MYSQL_PASSWORD: "your-secure-password"
  
  # Example rclone config for Google Cloud Storage
  RCLONE_CONFIG: |
    [mygcs]
    type = google cloud storage
    project_number = your-project-id
    service_account_file = /etc/gcs-key/key.json
    location = us-central1
    storage_class = STANDARD