name: Documentation

# Validates documentation structure, links, YAML syntax, and quality
# Updated to support new clean README.md structure with separate doc files

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - 'docs/**'
      - '**.yaml'
      - '**.yml'
      - 'config.yaml.example'
      - 'docker-compose.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'
      - 'docs/**'
      - '**.yaml'
      - '**.yml'
      - 'config.yaml.example'
      - 'docker-compose.yml'

jobs:
  validate-docs:
    name: Validate Documentation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Validate README.md
      run: |
        echo "🔍 Validating README.md..."
        
        # Check if README.md exists
        if [ ! -f "README.md" ]; then
          echo "❌ README.md not found"
          exit 1
        fi
        
        # Check if README.md contains required sections
        required_sections=("Quick Start" "Key Features" "Documentation" "Basic Usage")
        for section in "${required_sections[@]}"; do
          if ! grep -q "## .*$section" README.md; then
            echo "❌ Missing section: $section"
            exit 1
          fi
        done
        
        echo "✅ README.md validation passed"
    
    - name: Validate YAML files
      run: |
        echo "🔍 Validating YAML files..."
        
        # Function to check YAML syntax
        check_yaml_syntax() {
          local file="$1"
          echo "Checking $file..."
          
          # Use Ruby for consistent validation (works for both single and multi-document)
          ruby -e "
            require 'yaml'
            begin
              # Load all documents for multi-document YAML support
              docs = YAML.load_stream(File.read('$file'))
              # Filter out nil documents
              valid_docs = docs.compact
              puts '✅ $file: Valid YAML syntax (' + valid_docs.length.to_s + ' document(s))'
            rescue => e
              puts '❌ $file: Invalid YAML syntax'
              puts 'Error: ' + e.message
              exit 1
            end
          " || return 1
        }
        
        # Check config.yaml.example
        if [ -f "config.yaml.example" ]; then
          check_yaml_syntax "config.yaml.example"
        fi
        
        # Check docker-compose.yml
        if [ -f "docker-compose.yml" ]; then
          check_yaml_syntax "docker-compose.yml"
        fi
        
        # Check other YAML files
        find . -name "*.yml" -o -name "*.yaml" | grep -v .github | while read file; do
          if [ -f "$file" ]; then
            check_yaml_syntax "$file"
          fi
        done
        
        echo "✅ All YAML files have valid syntax"
    
    - name: Check documentation links
      run: |
        echo "🔍 Checking documentation links..."
        
        # Check if referenced documentation files exist
        docs_files=(
          "INSTALL.md" 
          "DOCKER.md" 
          "TROUBLESHOOTING.md"
          "MYSQL_USER_SETUP.md" 
          "PRODUCTION_DEPLOYMENT.md"
          "docs/COMMANDS.md"
          "config.yaml.example"
        )
        
        missing_files=()
        found_files=()
        
        for doc in "${docs_files[@]}"; do
          if grep -q "$doc" README.md; then
            if [ ! -f "$doc" ]; then
              missing_files+=("$doc")
              echo "❌ Referenced but missing: $doc"
            else
              found_files+=("$doc")
              echo "✅ Found: $doc"
            fi
          fi
        done
        
        # Check for new documentation files that should be referenced
        new_docs=("TROUBLESHOOTING.md" "DOCKER.md")
        for doc in "${new_docs[@]}"; do
          if [ -f "$doc" ] && ! grep -q "$doc" README.md; then
            echo "⚠️  Documentation file exists but not referenced in README: $doc"
          fi
        done
        
        if [ ${#missing_files[@]} -gt 0 ]; then
          echo "❌ Missing ${#missing_files[@]} referenced files"
          exit 1
        fi
        
        echo "✅ Documentation links check completed"
    
    - name: Validate documentation structure
      run: |
        echo "🔍 Validating documentation structure..."
        
        # Check TROUBLESHOOTING.md structure
        if [ -f "TROUBLESHOOTING.md" ]; then
          echo "Checking TROUBLESHOOTING.md..."
          required_sections=("Common Issues" "MySQL Setup" "Docker Issues" "Getting Help")
          for section in "${required_sections[@]}"; do
            if ! grep -q "## .*$section" TROUBLESHOOTING.md; then
              echo "⚠️  TROUBLESHOOTING.md missing section: $section"
            else
              echo "✅ Found section: $section"
            fi
          done
        fi
        
        # Check DOCKER.md structure
        if [ -f "DOCKER.md" ]; then
          echo "Checking DOCKER.md..."
          required_sections=("Quick Start" "Interactive Setup" "Networking" "Volume Mounts")
          for section in "${required_sections[@]}"; do
            if ! grep -q "## .*$section" DOCKER.md; then
              echo "⚠️  DOCKER.md missing section: $section"
            else
              echo "✅ Found section: $section"
            fi
          done
        fi
        
        # Check if Docker examples are properly formatted
        if [ -f "DOCKER.md" ]; then
          if ! grep -q "docker pull ghcr.io/abdullahainun/tenangdb:latest" DOCKER.md; then
            echo "⚠️  DOCKER.md missing verified docker pull command"
          else
            echo "✅ Docker pull command found"
          fi
        fi
        
        # Validate README.md links point to existing files
        echo "Checking README.md documentation links..."
        while IFS= read -r line; do
          if [[ $line =~ \[.*\]\(([^)]+)\) ]]; then
            link="${BASH_REMATCH[1]}"
            # Skip external URLs and anchors
            if [[ ! $link =~ ^https?:// ]] && [[ ! $link =~ ^# ]] && [[ $link != *"#"* ]]; then
              if [ ! -f "$link" ] && [ ! -d "$link" ]; then
                echo "⚠️  Broken link in README.md: $link"
              else
                echo "✅ Valid link: $link"
              fi
            fi
          fi
        done < README.md
        
        echo "✅ Documentation structure validation completed"
    
    - name: Validate Docker Compose
      if: hashFiles('docker-compose.yml') != ''
      run: |
        echo "🔍 Validating Docker Compose..."
        
        # Check if docker-compose.yml exists
        if [ ! -f "docker-compose.yml" ]; then
          echo "⚠️  docker-compose.yml not found, skipping validation"
          exit 0
        fi
        
        # Validate docker-compose.yml syntax and structure
        python3 -c "
        import yaml
        import sys
        
        try:
            with open('docker-compose.yml', 'r') as f:
                compose_data = yaml.safe_load(f)
            
            print('✅ Docker Compose YAML syntax is valid')
            
            # Check if it has services section
            if 'services' not in compose_data:
                print('⚠️  No services section found in docker-compose.yml')
            else:
                services = compose_data['services']
                print(f'✅ Found {len(services)} service(s): {list(services.keys())}')
                
                # Check for tenangdb service
                if 'tenangdb' in services:
                    print('✅ tenangdb service found')
                else:
                    print('⚠️  No tenangdb service found in docker-compose.yml')
        
        except yaml.YAMLError as e:
            print('❌ Docker Compose YAML syntax error')
            print(f'Error: {e}')
            sys.exit(1)
        except Exception as e:
            print('❌ Error reading docker-compose.yml')
            print(f'Error: {e}')
            sys.exit(1)
        "
        
        echo "✅ Docker Compose validation completed"
    
    - name: Check documentation quality
      run: |
        echo "🔍 Checking documentation quality..."
        
        # Check README.md length (should be concise)
        readme_lines=$(wc -l < README.md)
        if [ $readme_lines -gt 100 ]; then
          echo "⚠️  README.md is quite long ($readme_lines lines). Consider moving content to separate files."
        else
          echo "✅ README.md length is appropriate ($readme_lines lines)"
        fi
        
        # Check for consistent emoji usage
        if ! grep -q "🛡️" README.md; then
          echo "⚠️  Missing main project emoji (🛡️) in README.md"
        else
          echo "✅ Main project emoji found"
        fi
        
        # Check for installation commands
        if ! grep -q "curl.*tenangdb-install.sh" README.md; then
          echo "⚠️  Missing installation command in README.md"
        else
          echo "✅ Installation command found"
        fi
        
        # Check for demo link
        if ! grep -q "asciinema.org" README.md; then
          echo "⚠️  Missing demo link in README.md"
        else
          echo "✅ Demo link found"
        fi
        
        # Check for proper badge formatting
        badge_count=$(grep -c "shields.io\|img.shields.io" README.md || true)
        if [ $badge_count -lt 3 ]; then
          echo "⚠️  Less than 3 badges found ($badge_count). Consider adding more status badges."
        else
          echo "✅ Found $badge_count badges"
        fi
        
        # Check for proper code block formatting
        bash_blocks=$(grep -c "```bash" README.md || true)
        if [ $bash_blocks -lt 3 ]; then
          echo "⚠️  Few bash code blocks found ($bash_blocks). Users need clear examples."
        else
          echo "✅ Found $bash_blocks bash code blocks"
        fi
        
        echo "✅ Documentation quality check completed"

  status-check:
    name: Documentation Status Check
    runs-on: ubuntu-latest
    needs: [validate-docs]
    if: always()
    steps:
    - name: Check validation results
      run: |
        if [ "${{ needs.validate-docs.result }}" != "success" ]; then
          echo "❌ Documentation validation failed: ${{ needs.validate-docs.result }}"
          exit 1
        fi
        echo "✅ All documentation checks passed!"