name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - 'docs/**'
      - '**.yaml'
      - '**.yml'
      - 'config.yaml.example'
      - 'docker-compose.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'
      - 'docs/**'
      - '**.yaml'
      - '**.yml'
      - 'config.yaml.example'
      - 'docker-compose.yml'

jobs:
  validate-docs:
    name: Validate Documentation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Validate README.md
      run: |
        echo "🔍 Validating README.md..."
        
        # Check if README.md exists
        if [ ! -f "README.md" ]; then
          echo "❌ README.md not found"
          exit 1
        fi
        
        # Check if README.md contains required sections
        required_sections=("Quick Start" "Config" "Features" "Commands")
        for section in "${required_sections[@]}"; do
          if ! grep -q "## .*$section" README.md; then
            echo "❌ Missing section: $section"
            exit 1
          fi
        done
        
        echo "✅ README.md validation passed"
    
    - name: Validate YAML files
      run: |
        echo "🔍 Validating YAML files..."
        
        # Function to check YAML syntax
        check_yaml_syntax() {
          local file="$1"
          echo "Checking $file..."
          
          # Use Ruby for consistent validation (works for both single and multi-document)
          ruby -e "
            require 'yaml'
            begin
              # Load all documents for multi-document YAML support
              docs = YAML.load_stream(File.read('$file'))
              # Filter out nil documents
              valid_docs = docs.compact
              puts '✅ $file: Valid YAML syntax (' + valid_docs.length.to_s + ' document(s))'
            rescue => e
              puts '❌ $file: Invalid YAML syntax'
              puts 'Error: ' + e.message
              exit 1
            end
          " || return 1
        }
        
        # Check config.yaml.example
        if [ -f "config.yaml.example" ]; then
          check_yaml_syntax "config.yaml.example"
        fi
        
        # Check docker-compose.yml
        if [ -f "docker-compose.yml" ]; then
          check_yaml_syntax "docker-compose.yml"
        fi
        
        # Check other YAML files
        find . -name "*.yml" -o -name "*.yaml" | grep -v .github | while read file; do
          if [ -f "$file" ]; then
            check_yaml_syntax "$file"
          fi
        done
        
        echo "✅ All YAML files have valid syntax"
    
    - name: Check documentation links
      run: |
        echo "🔍 Checking documentation links..."
        
        # Check if referenced documentation files exist
        docs_files=("INSTALL.md" "DOCKER.md" "MYSQL_USER_SETUP.md" "PRODUCTION_DEPLOYMENT.md")
        for doc in "${docs_files[@]}"; do
          if grep -q "$doc" README.md; then
            if [ ! -f "$doc" ]; then
              echo "⚠️  Referenced but missing: $doc"
            else
              echo "✅ Found: $doc"
            fi
          fi
        done
        
        echo "✅ Documentation links check completed"
    
    - name: Validate Docker Compose
      if: hashFiles('docker-compose.yml') != ''
      run: |
        echo "🔍 Validating Docker Compose..."
        
        # Check if docker-compose.yml exists
        if [ ! -f "docker-compose.yml" ]; then
          echo "⚠️  docker-compose.yml not found, skipping validation"
          exit 0
        fi
        
        # Validate docker-compose.yml syntax and structure
        python3 -c "
        import yaml
        import sys
        
        try:
            with open('docker-compose.yml', 'r') as f:
                compose_data = yaml.safe_load(f)
            
            print('✅ Docker Compose YAML syntax is valid')
            
            # Check if it has services section
            if 'services' not in compose_data:
                print('⚠️  No services section found in docker-compose.yml')
            else:
                services = compose_data['services']
                print(f'✅ Found {len(services)} service(s): {list(services.keys())}')
                
                # Check for tenangdb service
                if 'tenangdb' in services:
                    print('✅ tenangdb service found')
                else:
                    print('⚠️  No tenangdb service found in docker-compose.yml')
        
        except yaml.YAMLError as e:
            print('❌ Docker Compose YAML syntax error')
            print(f'Error: {e}')
            sys.exit(1)
        except Exception as e:
            print('❌ Error reading docker-compose.yml')
            print(f'Error: {e}')
            sys.exit(1)
        "
        
        echo "✅ Docker Compose validation completed"

  status-check:
    name: Documentation Status Check
    runs-on: ubuntu-latest
    needs: [validate-docs]
    if: always()
    steps:
    - name: Check validation results
      run: |
        if [ "${{ needs.validate-docs.result }}" != "success" ]; then
          echo "❌ Documentation validation failed: ${{ needs.validate-docs.result }}"
          exit 1
        fi
        echo "✅ All documentation checks passed!"